set(MJ_KDL_VERSION "0.3.9")
set(MJ_KDL_MUJOCO_VERSION "3.9.0")

if(NOT MJ_KDL_MUJOCO_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
  message(FATAL_ERROR "Invalid MJ_KDL_MUJOCO_VERSION: ${MJ_KDL_MUJOCO_VERSION}")
endif()

set(MJ_KDL_MUJOCO_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(MJ_KDL_MUJOCO_VERSION_MINOR "${CMAKE_MATCH_2}")
set(MJ_KDL_MUJOCO_VERSION_PATCH "${CMAKE_MATCH_3}")
math(
  EXPR
  MJ_KDL_MUJOCO_VERSION_HEADER
  "${MJ_KDL_MUJOCO_VERSION_MAJOR} * 1000000 + ${MJ_KDL_MUJOCO_VERSION_MINOR} * 1000 + ${MJ_KDL_MUJOCO_VERSION_PATCH}"
)
